ktor:
  deployment:
    port: 8080

  application:
    modules:
      - com.example.ApplicationKt.module

jwt:
  issuer: "http://0.0.0.0:8080/"
  audience: "users"
  secret: "super_secret_jwt_key_123456789"